global:
  scrape_interval: 10s

scrape_configs:
  - job_name: consul
    metrics_path: /metrics
    consul_sd_configs:
      - server: 'consul_server_0:8500'
    relabel_configs:
      - source_labels:
        - __meta_consul_tagged_address_lan
        - __meta_consul_service_metadata_prometheus_port
        regex: '(.*);(.*)'
        replacement: '${1}:${2}'
        target_label: '__address__'
        action: 'replace'
